import { Hono } from "hono";
import { stream } from "hono/streaming";
import { z } from "zod";
import type { Agent } from "@mastra/core/agent";
import type { MastraMemory } from "@mastra/core/memory";
import { ragConfig } from "../config/rag.config.js";
import { extractSources } from "../../../api/helpers/extract-sources.js";
import { buildAgentOptions } from "../../../application/agent-context.js";
import type { ConversationManager } from "../../../application/managers/conversation.manager.js";
import type { AttachmentStore } from "../../../domain/ports/attachment-store.js";
import { scheduleTitleSync } from "../../../application/title-sync.js";

const chatSchema = z.object({
  query: z.string().min(1).max(10_000),
  conversationId: z.string().uuid().optional(),
  documentIds: z.array(z.string().uuid()).optional(),
});

/**
 * Factory: creates chat routes bound to a specific RAG agent instance.
 */
export function createChatRoutes(agent: Agent, convManager: ConversationManager, memory?: MastraMemory, attachmentStore?: AttachmentStore): Hono {
  const chat = new Hono();

  /**
   * POST /chat
   * Non-streaming: agent decides which tools to call, returns complete answer.
   */
  chat.post("/", async (c) => {
    const body = await c.req.json().catch(() => null);
    const parsed = chatSchema.safeParse(body);

    if (!parsed.success) {
      return c.json({ error: parsed.error.message }, 400);
    }

    const { query } = parsed.data;
    const orgId = c.get("user")?.orgId;
    if (!orgId) return c.json({ error: "Unauthorized", message: "Missing orgId" }, 401);
    const userId = c.get("user")?.userId;
    const conversationId = await resolveConversationId(parsed.data.conversationId, convManager, userId, query);

    const agentOptions = buildAgentOptions({ userId: userId ?? "anonymous", orgId, conversationId });

    const result = await agent.generate(query, agentOptions);

    const sources = extractSources(result.steps ?? []);

    await convManager.persistMessages(conversationId, query, result.text, {
      model: ragConfig.llmModel,
      retrievedChunks: sources.map((s) => s.id),
    });

    if (memory) scheduleTitleSync(memory, conversationId, convManager);

    return c.json({
      conversationId,
      answer: result.text,
      sources,
      metadata: {
        model: ragConfig.llmModel,
        chunksRetrieved: sources.length,
      },
    });
  });

  /**
   * GET /chat/stream?query=...&conversationId=...
   * SSE streaming using Mastra's native chunk types.
   *
   * Events emitted:
   *   tool-call        → agent is about to call a tool
   *   tool-result      → tool finished (only for specific tools like searchDocuments)
   *   tool-error       → tool failed
   *   agent-start      → coordinator delegated to a sub-agent
   *   agent-end        → sub-agent finished
   *   step-start       → LLM step started
   *   step-finish      → LLM step completed
   *   sources          → RAG sources extracted from searchDocuments
   *   attachment       → PDF generated by calculateBudget
   *   text             → text token from the agent
   *   error            → something failed
   *   done             → stream finished
   */
  chat.get("/stream", async (c) => {
    const queryParam = c.req.query("query");
    const conversationIdParam = c.req.query("conversationId");
    const orgId = c.get("user")?.orgId;
    const userId = c.get("user")?.userId;

    if (!orgId) return c.json({ error: "Unauthorized", message: "Missing orgId" }, 401);

    if (!queryParam?.trim()) {
      return c.json({ error: "Missing 'query' query parameter" }, 400);
    }

    const parsed = chatSchema.safeParse({
      query: queryParam,
      conversationId: conversationIdParam ?? undefined,
    });

    if (!parsed.success) {
      return c.json({ error: parsed.error.message }, 400);
    }

    const conversationId = await resolveConversationId(parsed.data.conversationId, convManager, userId, parsed.data.query);

    c.header("Content-Type", "text/event-stream");
    c.header("Cache-Control", "no-cache");
    c.header("Connection", "keep-alive");
    c.header("X-Conversation-Id", conversationId);

    return stream(c, async (streamWriter) => {
      let fullAnswer = "";
      let sourcesEmitted = false;
      const collectedSources: Array<{ id: string; documentTitle: string; documentSource: string; score: number; excerpt: string }> = [];

      /** Helper: emit an SSE event */
      const emit = (data: Record<string, unknown>) =>
        streamWriter.write(`data: ${JSON.stringify(data)}\n\n`);

      try {
        const agentOptions = buildAgentOptions({
          userId: userId ?? "anonymous",
          orgId,
          conversationId,
          onFinish: async ({ text }) => {
            // Persist messages via hook — runs after stream completes
            if (text) {
              try {
                await convManager.persistMessages(conversationId, parsed.data.query, text, {
                  model: ragConfig.llmModel,
                  retrievedChunks: collectedSources.map((s) => s.id),
                });
                if (memory) scheduleTitleSync(memory, conversationId, convManager);
              } catch (err) {
                console.error("[chat/stream] failed to persist messages:", err instanceof Error ? err.message : err);
              }
            }
          },
          delegation: {
            onDelegationStart: ({ primitiveId, parentAgentName }) => {
              console.log(`[delegation] ${parentAgentName} → ${primitiveId}`);
            },
            onDelegationComplete: ({ primitiveId, duration, success, error }) => {
              console.log(`[delegation] ${primitiveId} completed in ${(duration / 1000).toFixed(1)}s (success=${success}${error ? `, error=${error.message}` : ""})`);
            },
          },
        });

        const agentStream = await agent.stream(parsed.data.query, agentOptions);

        for await (const chunk of agentStream.fullStream) {
          const payload = (chunk as { payload?: Record<string, unknown> }).payload ?? {};

          switch (chunk.type) {
            // ── Tool lifecycle ──────────────────────────────────────
            case "tool-call": {
              const toolName = payload["toolName"] as string | undefined;
              if (toolName) {
                await emit({ type: "tool-call", toolName });
              }
              break;
            }

            case "tool-result": {
              const toolName = payload["toolName"] as string | undefined;

              // Extract RAG sources from searchDocuments
              if (toolName === "searchDocuments" && !sourcesEmitted) {
                const res = payload["result"] as {
                  chunks?: Array<{ id: string; content: string; documentTitle: string; documentSource: string; score: number }>;
                } | undefined;
                const chunks = res?.chunks ?? [];
                collectedSources.push(
                  ...chunks.map((ch) => ({
                    id: ch.id,
                    documentTitle: ch.documentTitle,
                    documentSource: ch.documentSource ?? "",
                    score: ch.score,
                    excerpt: ch.content?.slice(0, 200) + (ch.content?.length > 200 ? "…" : ""),
                  }))
                );
                await emit({ type: "sources", chunks: collectedSources });
                sourcesEmitted = true;
              }

              // Extract PDF attachments (may be nested inside sub-agent delegation)
              if (attachmentStore) {
                const filename = findPdfFilename(payload["result"]);
                if (filename) {
                  const stored = attachmentStore.retrieve(filename);
                  if (stored) {
                    await emit({ type: "attachment", filename: stored.filename, base64: stored.base64 });
                  }
                }
              }
              break;
            }

            case "tool-error": {
              const toolName = payload["toolName"] as string | undefined;
              const error = payload["error"] as string | undefined;
              await emit({ type: "tool-error", toolName: toolName ?? "unknown", error: error ?? "Unknown tool error" });
              break;
            }

            // ── Sub-agent delegation (Supervisor Pattern) ──────────
            case "agent-execution-start": {
              const agentId = payload["agentId"] as string | undefined;
              await emit({ type: "agent-start", agentId: agentId ?? "unknown" });
              break;
            }

            case "agent-execution-end": {
              const agentId = payload["agentId"] as string | undefined;
              await emit({ type: "agent-end", agentId: agentId ?? "unknown" });
              break;
            }

            // ── LLM steps ──────────────────────────────────────────
            case "step-start": {
              await emit({ type: "step-start" });
              break;
            }

            case "step-finish": {
              const finishReason = payload["finishReason"] as string | undefined;
              await emit({ type: "step-finish", finishReason: finishReason ?? "unknown" });
              break;
            }

            // ── Text output ────────────────────────────────────────
            case "text-delta": {
              const text = (payload["text"] as string | undefined) ?? "";
              if (text) {
                fullAnswer += text;
                await emit({ type: "text", text });
              }
              break;
            }

            // Other chunk types (reasoning, object, etc.) — skip
            default:
              break;
          }
        }

        if (!sourcesEmitted) {
          await emit({ type: "sources", chunks: [] });
        }

        // Fallback persistence if onFinish didn't fire (e.g. empty response)
        // onFinish should handle this, but belt-and-suspenders for reliability
        if (!fullAnswer) {
          // No text generated — nothing to persist
        }
      } catch (error) {
        const msg = error instanceof Error ? error.message : "Internal error";
        await emit({ type: "error", message: msg });
      } finally {
        await emit({ type: "done" });
      }
    });
  });

  return chat;
}

// ============================================================
// Helpers
// ============================================================

/**
 * Recursively searches a tool result for { pdfGenerated: true, filename: "*.pdf" }.
 * Handles both direct calculateBudget results and nested sub-agent delegation results.
 */
function findPdfFilename(obj: unknown, depth = 0): string | null {
  if (!obj || typeof obj !== "object" || depth > 5) return null;

  const record = obj as Record<string, unknown>;

  // Direct match: calculateBudget result shape
  if (record["pdfGenerated"] === true && typeof record["filename"] === "string") {
    return record["filename"] as string;
  }

  // Recurse into nested objects/arrays (sub-agent delegation wraps results)
  for (const value of Object.values(record)) {
    if (Array.isArray(value)) {
      for (const item of value) {
        const found = findPdfFilename(item, depth + 1);
        if (found) return found;
      }
    } else if (value && typeof value === "object") {
      const found = findPdfFilename(value, depth + 1);
      if (found) return found;
    }
  }

  return null;
}

async function resolveConversationId(
  id: string | undefined,
  convManager: ConversationManager,
  userId?: string,
  query?: string,
): Promise<string> {
  if (id) {
    try {
      await convManager.getById(id);
      return id;
    } catch {
      // conversation may have been deleted — create a new one
    }
  }

  const title = query && query.length > 60
    ? query.slice(0, 60) + "..."
    : query || "New conversation";

  const conv = await convManager.create({ userId, title });
  return conv.id;
}
