import { logger } from "../../../shared/logger.js";
import { Hono } from "hono";
import { stream } from "hono/streaming";
import { z } from "zod";
import type { AgentRunner } from "../../../agent/agent-runner.js";
import type { DelegationResult } from "../../../agent/types.js";
import { extractToolSummaries, summarizeToolCall } from "../../../agent/tool-summaries.js";
import { ragConfig } from "../config/rag.config.js";
import { extractSources } from "../../../api/helpers/extract-sources.js";
import { findPdfFilename } from "../../../api/helpers/find-pdf-filename.js";
import { createAgentContext } from "../../../application/agent-context.js";
import { loadConversationHistory } from "../../../agent/load-history.js";
import type { ConversationManager } from "../../../application/managers/conversation.manager.js";
import type { AttachmentStore } from "../../../domain/ports/attachment-store.js";
import type { ToolCallSummary } from "../../../domain/entities/index.js";

const chatSchema = z.object({
  query: z.string().min(1).max(10_000),
  conversationId: z.string().uuid().optional(),
  documentIds: z.array(z.string().uuid()).optional(),
});

/**
 * Factory: creates chat routes bound to a specific agent instance.
 */
export function createChatRoutes(agent: AgentRunner, convManager: ConversationManager, attachmentStore?: AttachmentStore): Hono {
  const chat = new Hono();

  /**
   * POST /chat
   * Non-streaming: agent decides which tools to call, returns complete answer.
   */
  chat.post("/", async (c) => {
    const body = await c.req.json().catch(() => null);
    const parsed = chatSchema.safeParse(body);

    if (!parsed.success) {
      return c.json({ error: parsed.error.message }, 400);
    }

    const { query } = parsed.data;
    const orgId = c.get("user")?.orgId;
    if (!orgId) return c.json({ error: "Unauthorized", message: "Missing orgId" }, 401);
    const userId = c.get("user")?.userId;
    const conversationId = await resolveConversationId(parsed.data.conversationId, convManager, userId, query);

    const experimental_context = createAgentContext({ userId: userId ?? "anonymous", orgId, conversationId });
    const history = await loadConversationHistory(convManager, conversationId);

    const result = await agent.generate({ prompt: query, messages: history, experimental_context });

    const sources = extractSources(result.steps);
    const toolSummaries = extractToolSummaries(result.steps);

    await convManager.persistMessages(conversationId, query, result.text, {
      model: ragConfig.llmModel,
      retrievedChunks: sources.map((s) => s.id),
      toolCalls: toolSummaries,
    });

    return c.json({
      conversationId,
      answer: result.text,
      sources,
      metadata: {
        model: ragConfig.llmModel,
        chunksRetrieved: sources.length,
      },
    });
  });

  /**
   * GET /chat/stream?query=...&conversationId=...
   * SSE streaming.
   *
   * Events emitted:
   *   tool-call        → agent is about to call a tool
   *   tool-result      → tool finished (only for specific tools like searchDocuments)
   *   tool-error       → tool failed
   *   step-start       → LLM step started
   *   step-finish      → LLM step completed
   *   sources          → RAG sources extracted from searchDocuments
   *   attachment       → PDF generated by calculateBudget
   *   text             → text token from the agent
   *   error            → something failed
   *   done             → stream finished
   */
  chat.get("/stream", async (c) => {
    const queryParam = c.req.query("query");
    const conversationIdParam = c.req.query("conversationId");
    const orgId = c.get("user")?.orgId;
    const userId = c.get("user")?.userId;

    if (!orgId) return c.json({ error: "Unauthorized", message: "Missing orgId" }, 401);

    if (!queryParam?.trim()) {
      return c.json({ error: "Missing 'query' query parameter" }, 400);
    }

    const parsed = chatSchema.safeParse({
      query: queryParam,
      conversationId: conversationIdParam ?? undefined,
    });

    if (!parsed.success) {
      return c.json({ error: parsed.error.message }, 400);
    }

    const conversationId = await resolveConversationId(parsed.data.conversationId, convManager, userId, parsed.data.query);

    c.header("Content-Type", "text/event-stream");
    c.header("Cache-Control", "no-cache");
    c.header("Connection", "keep-alive");
    c.header("X-Conversation-Id", conversationId);

    return stream(c, async (streamWriter) => {
      let fullAnswer = "";
      let sourcesEmitted = false;
      let attachmentEmitted = false;
      const collectedSources: Array<{ id: string; documentTitle: string; documentSource: string; score: number; excerpt: string }> = [];
      const collectedToolSummaries: ToolCallSummary[] = [];

      /** Helper: emit an SSE event */
      const emit = (data: Record<string, unknown>) =>
        streamWriter.write(`data: ${JSON.stringify(data)}\n\n`);

      try {
        const experimental_context = createAgentContext({
          userId: userId ?? "anonymous",
          orgId,
          conversationId,
        });
        const history = await loadConversationHistory(convManager, conversationId);

        // Persist user message BEFORE streaming — survives stream failures
        try {
          await convManager.persistUserMessage(conversationId, parsed.data.query);
        } catch (err) {
          logger.error({ err }, "Failed to persist user message");
        }

        const agentStream = await agent.stream({
          prompt: parsed.data.query,
          messages: history,
          experimental_context,
        });

        for await (const chunk of agentStream.fullStream) {
          switch (chunk.type) {
            // ── Tool lifecycle ──────────────────────────────────────
            case "tool-call": {
              const toolName = (chunk as { toolName?: string }).toolName;
              if (toolName) {
                // Delegation tools → emit agent-start for frontend activity indicators
                if (toolName.startsWith("delegateTo_")) {
                  const agentId = "agent-" + toolName.replace("delegateTo_", "");
                  await emit({ type: "agent-start", agentId });
                } else {
                  await emit({ type: "tool-call", toolName });
                }
              }
              break;
            }

            case "tool-result": {
              const toolName = (chunk as { toolName?: string }).toolName;
              // AI SDK v6 streams use "output" (not "result") for tool-result chunks
              const result = (chunk as { output?: unknown }).output ?? (chunk as { result?: unknown }).result;

              // Collect tool summaries for persistence (cross-turn memory)
              if (toolName) {
                collectedToolSummaries.push({
                  toolName,
                  summary: summarizeToolCall({ toolName, result }),
                });
              }

              // Delegation tool results → emit agent-end + extract nested sources/attachments
              if (toolName?.startsWith("delegateTo_")) {
                const agentId = "agent-" + toolName.replace("delegateTo_", "");
                await emit({ type: "agent-end", agentId });

                // Extract sources from nested RAG delegation — uses typed DelegationResult
                if (!sourcesEmitted) {
                  const delegation = result as DelegationResult | undefined;
                  const ragResults = delegation?.toolResults?.filter((tr) => tr.toolName === "searchDocuments") ?? [];
                  for (const sr of ragResults) {
                    const res = sr.result as {
                      chunks?: Array<{ id: string; content: string; documentTitle: string; documentSource: string; score: number }>;
                    } | undefined;
                    const chunks = res?.chunks ?? [];
                    collectedSources.push(
                      ...chunks.map((ch) => ({
                        id: ch.id,
                        documentTitle: ch.documentTitle,
                        documentSource: ch.documentSource ?? "",
                        score: ch.score,
                        excerpt: ch.content?.slice(0, 200) + (ch.content?.length > 200 ? "…" : ""),
                      }))
                    );
                  }
                  if (collectedSources.length > 0) {
                    await emit({ type: "sources", chunks: collectedSources });
                    sourcesEmitted = true;
                  }
                }
              }

              // Direct tool sources (searchDocuments called directly, not via delegation)
              if (toolName === "searchDocuments" && !sourcesEmitted) {
                const res = result as {
                  chunks?: Array<{ id: string; content: string; documentTitle: string; documentSource: string; score: number }>;
                } | undefined;
                const chunks = res?.chunks ?? [];
                collectedSources.push(
                  ...chunks.map((ch) => ({
                    id: ch.id,
                    documentTitle: ch.documentTitle,
                    documentSource: ch.documentSource ?? "",
                    score: ch.score,
                    excerpt: ch.content?.slice(0, 200) + (ch.content?.length > 200 ? "…" : ""),
                  }))
                );
                await emit({ type: "sources", chunks: collectedSources });
                sourcesEmitted = true;
              }

              // Extract PDF attachments ONLY from quote-related tools (not from gmail/calendar/etc.)
              // This prevents re-sending a PDF when the gmail agent sends it as an attachment.
              if (attachmentStore && !attachmentEmitted) {
                const isQuoteTool = toolName === "calculateBudget" || toolName === "delegateTo_quote";
                if (isQuoteTool) {
                  const filename = findPdfFilename(result);
                  if (filename) {
                    const stored = await attachmentStore.retrieve(userId ?? "anonymous", filename);
                    if (stored) {
                      await emit({ type: "attachment", filename: stored.filename, base64: stored.base64 });
                      attachmentEmitted = true;
                    }
                  }
                }
              }
              break;
            }

            case "tool-error": {
              const toolName = (chunk as { toolName?: string }).toolName;
              const error = (chunk as { error?: string }).error;
              await emit({ type: "tool-error", toolName: toolName ?? "unknown", error: error ?? "Unknown tool error" });
              break;
            }

            // ── LLM steps ──────────────────────────────────────────
            case "start-step": {
              await emit({ type: "step-start" });
              break;
            }

            case "finish-step": {
              const finishReason = (chunk as { finishReason?: string }).finishReason;
              await emit({ type: "step-finish", finishReason: finishReason ?? "unknown" });
              break;
            }

            // ── Text output ────────────────────────────────────────
            case "text-delta": {
              const text = (chunk as { text?: string }).text ?? "";
              if (text) {
                fullAnswer += text;
                await emit({ type: "text", text });
              }
              break;
            }

            // ── Error from LLM ─────────────────────────────────
            case "error": {
              const error = chunk;
              logger.error({ err: error }, "Error chunk from agent");
              await emit({ type: "error", message: String((error as Record<string, unknown>)?.["message"] ?? error) });
              break;
            }

            // Other chunk types (reasoning, text-start, text-end, etc.) — ignore silently
            default: {
              const ignoredTypes = new Set([
                "reasoning-delta", "reasoning-start", "reasoning-end",
                "text-start", "text-end",
                "tool-input-start", "tool-input-delta",
              ]);
              if (!ignoredTypes.has(chunk.type)) {
                logger.debug({ chunkType: chunk.type }, "Unhandled chunk type in chat stream");
              }
              break;
            }
          }
        }

        if (!sourcesEmitted) {
          await emit({ type: "sources", chunks: [] });
        }

        // Persist assistant message after stream completes (user message already saved)
        if (fullAnswer) {
          try {
            await convManager.persistAssistantMessage(conversationId, fullAnswer, {
              model: ragConfig.llmModel,
              retrievedChunks: collectedSources.map((s) => s.id),
              toolCalls: collectedToolSummaries,
            });
          } catch (err) {
            logger.error({ err }, "Failed to persist assistant message");
          }
        }
      } catch (error) {
        const msg = error instanceof Error ? error.message : "Internal error";
        await emit({ type: "error", message: msg });
      } finally {
        await emit({ type: "done" });
      }
    });
  });

  return chat;
}

// ============================================================
// Helpers
// ============================================================

async function resolveConversationId(
  id: string | undefined,
  convManager: ConversationManager,
  userId?: string,
  query?: string,
): Promise<string> {
  if (id) {
    try {
      await convManager.getById(id);
      return id;
    } catch {
      // conversation may have been deleted — create a new one
    }
  }

  const title = query && query.length > 60
    ? query.slice(0, 60) + "..."
    : query || "New conversation";

  const conv = await convManager.create({ userId, title });
  return conv.id;
}
