/**
 * In-memory store for PDF attachments generated by calculateBudget tool.
 *
 * Bypasses Mastra's opaque step/payload wrapping — the tool writes the PDF here,
 * and the controller reads it back after agent.generate() completes.
 *
 * Keyed by a per-request UUID passed via RequestContext('pdfRequestId').
 */

interface PdfEntry {
  pdfBase64: string;
  filename: string;
  timestamp: number;
}

const store = new Map<string, PdfEntry>();

const MAX_AGE_MS = 5 * 60 * 1000; // 5 minutes

function cleanup() {
  const now = Date.now();
  for (const [key, entry] of store) {
    if (now - entry.timestamp > MAX_AGE_MS) {
      store.delete(key);
    }
  }
}

export const pdfStore = {
  set(requestId: string, pdf: { pdfBase64: string; filename: string }) {
    cleanup();
    store.set(requestId, { ...pdf, timestamp: Date.now() });
  },

  take(requestId: string): { pdfBase64: string; filename: string } | null {
    const entry = store.get(requestId);
    if (!entry) return null;
    store.delete(requestId);
    return { pdfBase64: entry.pdfBase64, filename: entry.filename };
  },
};
