/**
 * In-memory store for PDF attachments generated by calculateBudget tool.
 *
 * Keyed by filename (e.g. "PRES-20260306-1234.pdf") which the tool always
 * generates deterministically. The controller extracts the filename from the
 * agent's text response via regex — no dependency on Mastra RequestContext
 * or step/payload propagation.
 */

interface PdfEntry {
  pdfBase64: string;
  filename: string;
  timestamp: number;
}

const store = new Map<string, PdfEntry>();

const MAX_AGE_MS = 5 * 60 * 1000; // 5 minutes

function cleanup() {
  const now = Date.now();
  for (const [key, entry] of store) {
    if (now - entry.timestamp > MAX_AGE_MS) {
      store.delete(key);
    }
  }
}

export const pdfStore = {
  set(filename: string, pdf: { pdfBase64: string; filename: string }) {
    cleanup();
    store.set(filename, { ...pdf, timestamp: Date.now() });
    console.log(`[pdfStore] stored PDF: ${filename} (${Math.round(pdf.pdfBase64.length / 1024)}KB)`);
  },

  take(filename: string): { pdfBase64: string; filename: string } | null {
    const entry = store.get(filename);
    if (!entry) {
      console.log(`[pdfStore] miss for: ${filename} (store has: ${[...store.keys()].join(", ") || "empty"})`);
      return null;
    }
    store.delete(filename);
    console.log(`[pdfStore] retrieved PDF: ${filename}`);
    return { pdfBase64: entry.pdfBase64, filename: entry.filename };
  },
};
