/**
 * In-memory store for PDF attachments generated by calculateBudget tool.
 *
 * Keyed by pdfRequestId (UUID) set by the controller in RequestContext.
 * The same RequestContext propagates orgId (proven to work through Mastra
 * delegation), so pdfRequestId propagates identically.
 *
 * Flow:
 *   Controller: generates pdfRequestId → puts in RequestContext
 *   Tool: reads pdfRequestId from context → stores PDF here
 *   Controller: retrieves PDF by the same pdfRequestId
 */

import { logger } from "../../../shared/logger.js";

interface PdfEntry {
  pdfBase64: string;
  filename: string;
  timestamp: number;
}

const store = new Map<string, PdfEntry>();

const MAX_AGE_MS = 5 * 60 * 1000; // 5 minutes

function cleanup() {
  const now = Date.now();
  for (const [key, entry] of store) {
    if (now - entry.timestamp > MAX_AGE_MS) {
      store.delete(key);
    }
  }
}

export const pdfStore = {
  set(requestId: string, pdf: { pdfBase64: string; filename: string }) {
    cleanup();
    store.set(requestId, { ...pdf, timestamp: Date.now() });
    logger.info({ filename: pdf.filename, key: requestId.slice(0, 8), sizeKB: Math.round(pdf.pdfBase64.length / 1024) }, "PDF stored");
  },

  take(requestId: string): { pdfBase64: string; filename: string } | null {
    const entry = store.get(requestId);
    if (!entry) {
      logger.info({ key: requestId.slice(0, 8), storeSize: store.size }, "PDF store miss");
      return null;
    }
    store.delete(requestId);
    logger.info({ filename: entry.filename, key: requestId.slice(0, 8) }, "PDF retrieved");
    return { pdfBase64: entry.pdfBase64, filename: entry.filename };
  },
};
